{
 "title": "ms sql instances dashboard",
 "description": "Performance and health metrics for MSSQL Servers using windows_exporter and Prometheus",
 "tags": [
  "mssql",
  "windows_exporter"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(windows_mssql_collector_duration_seconds, instance)"
    }
   },
   {
    "name": "dbinstance",
    "label": "DB Instance",
    "query": {
     "query": "label_values(windows_mssql_genstats_logical_connections{job=~\"$job.*\"}, mssql_instance)"
    }
   },
   { "name": "job", "query": "${VAR_JOB}" }
  ]
 },
 "panels": [
  { "title": "General Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "EXPORTER STATUS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$server.*\", job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "EXPORTER HEALTH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_collector_success{instance=~\"$server.*\", job=~\"node_exporter\"}"
    }
   ]
  },
  {
   "title": "DEADLOCKS",
   "type": "stat",
   "description": "**DEADLOCKS**\n\nNumber of lock requests per second that resulted in a deadlock since last restart",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_mars_deadlocks{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "RUIG",
   "type": "stat",
   "description": "**RUIG**\n\nNumber of duplicate tempdb recovery unit id generated.",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_tempdb_recovery_unit_ids_generated{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "LOGICAL CONNECTIONS",
   "type": "gauge",
   "description": "**LOGICAL CONNECTIONS**\n\nNumber of logical connections to the system.\n\nThe main purpose of logical connections is to service multiple active result sets (MARS) requests. For MARS requests, every time that an application makes a connection to SQL Server, there may be more than one logical connection that corresponds to a physical connection.\n\nWhen MARS is not used, the ratio between physical and logical connections is 1:1. Therefore, every time that an application makes a connection to SQL Server, logical connections will increase by 1.",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_logical_connections{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "NETWORK UTILIZATION (BETA)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(windows_net_bytes_total{instance=~\"$server.*\", job=~\"$job.*\"}[$interval])) / sum(windows_net_current_bandwidth{instance=~\"$server.*\", job=~\"$job.*\"}/8) * 10000"
    }
   ]
  },
  {
   "title": "LOGINS-LOGOUTS",
   "type": "bargauge",
   "description": "**LOGINS-LOGOUTS**\n\nTotal number of logins started per second. This does not include pooled connections.\n\nTotal number of logout operations started per second.",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_logins{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Logins/sec"
    },
    {
     "expr": "windows_mssql_genstats_logouts{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Logouts/sec"
    }
   ]
  },
  {
   "title": "SQL CPU",
   "type": "gauge",
   "description": "**SQL CPU**\n\nReturns elapsed time that all of the threads of this process used the processor to execute instructions by mode (privileged, user).",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (irate(process_cpu_seconds_total{job=~\"$job.*\", process=~\"sql.*\"}[30s]))"
    }
   ]
  },
  {
   "title": "tempDB FREE SPACE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_transactions_tempdb_free_space_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "ACTIVE TEMP TABLES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_active_temp_tables{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "LONGEST TRANSACT RUN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_transactions_longest_transaction_running_seconds{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "CONNECTIONS RESETS",
   "type": "stat",
   "description": "**CONNECTIONS RESETS**\n\nTotal number of logins started from the connection pool.",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_connection_resets{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "LOG USED",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (exported_instance) (windows_mssql_databases_log_used_percent{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})"
    }
   ]
  },
  {
   "title": "BYTES PER CONNECTION",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_instance) (windows_mssql_memmgr_connection_memory_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})"
    }
   ]
  },
  {
   "title": "DATA FILE SIZE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_instance) (windows_mssql_databases_data_files_size_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})"
    }
   ]
  },
  {
   "title": "LOCK WAITS I/O",
   "type": "stat",
   "description": "**LOCK WAITS I/O**\n\nSQL Trace IO Provider Lock Waits",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_sql_trace_io_provider_lock_waits{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "PLE",
   "type": "stat",
   "description": "**PLE**\n\nIndicates the number of seconds a page will stay in the buffer pool without references.",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_page_life_expectancy_seconds{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  { "title": "Database I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "PAGE READS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_page_reads{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "SQL READ I/O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (mode) (windows_process_io_bytes_total{instance=~\"$server.*\", job=~\"$job.*\", mode=\"read\", process=~\"sqlservr\"})"
    }
   ]
  },
  {
   "title": "PAGE WRITES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_page_writes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "SQL WRITE I/O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (mode) (windows_process_io_bytes_total{instance=~\"$server.*\", job=~\"$job.*\", mode=\"write\", process=~\"sqlservr\"})"
    }
   ]
  },
  {
   "title": "Reads | Rows Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(windows_process_io_operations_total{mode=\"read\", instance=~\"$server.*\"}[5m])",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Writes | Rows Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(windows_process_io_operations_total{mode=\"write\", instance=~\"$server.*\"}[5m])",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  { "title": "Performance Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "SQL Server Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_mssql_sqlstats_batch_requests{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Batch Requests/sec"
    },
    {
     "expr": "windows_mssql_genstats_user_connections{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "User Connections"
    },
    {
     "expr": "windows_mssql_genstats_logins{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Logins/sec"
    },
    {
     "expr": "windows_mssql_genstats_logouts{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Logouts/sec"
    },
    {
     "expr": "windows_mssql_sqlstats_sql_compilations{job=~\"$server.*\", exported_instance=~\"$dbinstance.*\"}",
     "legendFormat": "SQL Compilations/sec"
    },
    {
     "expr": "wmi_mssql_sqlstats_sql_recompilations{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "SQL Re-Compilations/sec"
    },
    {
     "expr": "windows_mssql_genstats_blocked_processes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Processes blocked"
    }
   ]
  },
  {
   "title": "Databases Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_transactions{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Transactions/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_write_transactions{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Write Transactions/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_log_flushes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Flushes/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_log_flush_wait_seconds{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Flush Wait Time"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_locks_lock_timeouts{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Lock Timeouts/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_group_commit_stall_seconds{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Group Stall/sec"
    },
    {
     "expr": "avg by (mssql_instance) (wmi_mssql_locks_lock_wait_seconds{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Lock Waits/sec"
    },
    {
     "expr": "avg by (mssql_instance) (wmi_mssql_databases_log_pool_disk_reads{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Pool Disc/sec"
    }
   ]
  },
  {
   "title": "Buffer Cache - Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_mssql_accessmethods_full_scans{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Full Scans/sec"
    },
    {
     "expr": "windows_mssql_accessmethods_index_searches{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Index Searches/sec"
    },
    {
     "expr": "windows_mssql_accessmethods_page_splits{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Page Splits/sec"
    },
    {
     "expr": "windows_mssql_bufman_page_lookups{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Page lookups/sec"
    },
    {
     "expr": "windows_mssql_bufman_page_reads{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Page reads/sec"
    },
    {
     "expr": "windows_mssql_bufman_page_writes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Page writes/sec"
    },
    {
     "expr": "windows_mssql_bufman_read_ahead_pages{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Readahead pages/sec"
    },
    {
     "expr": "windows_mssql_bufman_lazywrites{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Lazy writes/sec"
    },
    {
     "expr": "windows_mssql_bufman_checkpoint_pages{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Checkpoint pages/sec"
    }
   ]
  },
  {
   "title": "Memory Manager",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "windows_mssql_memmgr_sql_cache_memory_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "SQL Cache"
    },
    {
     "expr": "windows_mssql_memmgr_optimizer_memory_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Optimizer"
    },
    {
     "expr": "windows_mssql_memmgr_log_pool_memory_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Log Pool"
    },
    {
     "expr": "windows_mssql_memmgr_lock_memory_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Lock"
    },
    {
     "expr": "windows_mssql_memmgr_database_cache_memory_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Database Cache"
    },
    {
     "expr": "windows_mssql_memmgr_connection_memory_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Connection"
    }
   ]
  },
  {
   "title": "Lock Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"windows_mssql_locks_lock_requests.*\",job=~\"$job.*\"}, \"name\", \"$1\", \"__name__\", \"windows_mssql_locks_lock_requests(.*)\")",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Ratios",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_mssql_accessmethods_page_splits{job=~\"$job.*\"}",
     "legendFormat": "Pages split/batch request"
    },
    {
     "expr": "windows_mssql_sqlstats_sql_compilations{job=~\"$job.*\"}",
     "legendFormat": "SQL Compilation/batch request"
    },
    {
     "expr": "windows_mssql_bufman_page_reads{job=~\"$job.*\"}",
     "legendFormat": "Read-ahead/page read"
    },
    {
     "expr": "windows_mssql_sqlstats_sql_recompilations{job=~\"$job.*\"}",
     "legendFormat": "SQL Recompilation/batch request"
    }
   ]
  },
  {
   "title": "Database Size Trend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database | Rows Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_bulk_copy_rows.*\", instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Database | Log Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_log_files_size_bytes.*\", instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch | DLC Latency",
     "type": "graph",
     "description": "**Fetch | DLC Latency**\n\nAverage latency in microseconds between log blocks entering the Direct Log Consumer and being retrieved by the XTP controller, per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_xtp_controller_dlc_fetch_latency_seconds.*\", instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Peak | DLC Latency",
     "type": "graph",
     "description": "**Peak | DLC Latency**\n\nThe largest recorded latency, in microseconds, of a fetch from the Direct Log Consumer by the XTP controller.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_xtp_controller_dlc_fetch_latency_seconds.*\", instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log | Pool Activities",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_cache_misses{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Cache Misses/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_disk_reads{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Disk Reads/sec"
      },
      {
       "expr": "sum by (mssql_instance) (wmi_mssql_databases_log_pool_empty_free_pool_pushes{job=~\"$server.*\", exported_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Empty Free Pool Pushes/sec"
      },
      {
       "expr": "sum by (mssql_instance) (wmi_mssql_databases_log_pool_hash_deletes{job=~\"$server.*\", exported_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Hash Deletes/sec"
      },
      {
       "expr": "sum by (exported_instance) (windows_mssql_databases_log_pool_hash_inserts{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Hash Inserts/sec"
      },
      {
       "expr": "sum by (exported_instance) (windows_mssql_databases_log_pool_log_scan_pushes{job=~\"$server.*\", exported_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Log Scan Pushes/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_requests{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Requests/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_requests_old_vlf{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Requests Old VLF/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_total_shared_pool_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Total Shared Pool Bytes/sec"
      }
     ]
    },
    {
     "title": "Log | Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_files_size_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Files Size Bytes/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_files_used_size_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Files Used Size Bytes/sec"
      },
      {
       "expr": "sum by (mssql_instance) (wmi_mssql_databases_log_flush_wait_seconds{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Flush Wait Seconds/sec"
      },
      {
       "expr": "sum by (mssql_instance) (wmi_mssql_databases_log_flush_waits{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Flush Waits/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flush_write_seconds{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Flush Write Seconds/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flushed_bytes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Flushed Bytes/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flushes{instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Flushes/sec"
      }
     ]
    },
    {
     "title": "Database | Log Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_log_used_percent.*\", instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lock Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lock Wait Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=\"windows_mssql_locks_lock_wait_seconds\", instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ resource }}"
      }
     ]
    },
    {
     "title": "Lock Timeouts",
     "type": "graph",
     "description": "**Lock Timeouts**\n\nNumber of lock requests per second that timed out, but excluding requests for NOWAIT locks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace({__name__=\"windows_mssql_locks_lock_timeouts\", instance=~\"$server.*\", job=~\"$job.*\", mssql_instance=~\"$dbinstance.*\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ resource }}"
      }
     ]
    }
   ]
  }
 ]
}