{
 "title": "wireguard",
 "tags": [
  "wireguard",
  "network",
  "vpn"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interface", "query": { "query": "wireguard_received_bytes_total" } },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - wireguard_latest_handshake_seconds{interface=\"$interface\"}",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  },
  {
   "title": "Transmit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(wireguard_sent_bytes_total{interface=\"$interface\"}[5m])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Receive",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes_total{interface=\"$interface\"}[5m])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Transmit total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"$interface\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Receive total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"$interface\"}[$__range]))"
    }
   ]
  }
 ]
}