---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include the role
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  vars:
    grafana_ini:
      security:
        admin_user: admin
        admin_password: password
